import json
import base64
import urllib.parse
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from fpdf import FPDF
from io import BytesIO

router = APIRouter(prefix="/api/qr", tags=["QR"])

class PDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(41, 128, 185)  # Blue color
        self.cell(0, 10, 'MedBridge Digital Medical Record', 0, 1, 'C')
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 10, title, 0, 1, 'L', fill=True)
        self.ln(2)

    def chapter_body(self, label, text):
        self.set_font('helvetica', 'B', 11)
        self.cell(40, 8, f'{label}:', 0, 0)
        self.set_font('helvetica', '', 11)
        if not text or text == "N/A":
            self.set_text_color(150, 150, 150)
        self.multi_cell(0, 8, str(text) if text else "None reported")
        self.set_x(self.l_margin)
        self.set_text_color(0, 0, 0)

@router.get("/pdf", response_class=Response)
def generate_pdf_from_qr(payload: str):
    """
    Decodes the Base64 payload generated by the offline QR code
    and returns a beautifully structured PDF document.
    """
    try:
        # Decode the URL-encoded base64 payload
        decoded_b64 = base64.b64decode(payload).decode('utf-8')
        json_str = urllib.parse.unquote(decoded_b64)
        data = json.loads(json_str)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid payload format: {str(e)}")

    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    qr_type = data.get("t", "UNKNOWN")
    
    # Title based on QR type
    pdf.set_font('helvetica', 'B', 16)
    if qr_type == "SOS":
        pdf.set_text_color(192, 57, 43)  # Red
        pdf.cell(0, 10, 'EMERGENCY SOS SUMMARY', 0, 1, 'C')
    elif qr_type == "INTAKE":
        pdf.set_text_color(39, 174, 96)  # Green
        pdf.cell(0, 10, 'EXPRESS CLINIC INTAKE', 0, 1, 'C')
    else:
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, 'MEDICAL DATA SNAPSHOT', 0, 1, 'C')
        
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)
    
    # --- Patient Information ---
    pdf.chapter_title('Patient Identification')
    pdf.chapter_body('Full Name', data.get("n"))
    
    if qr_type == "INTAKE":
        if "e" in data: pdf.chapter_body('Email', data.get("e"))
        if "ph" in data: pdf.chapter_body('Phone', data.get("ph"))
    
    pdf.ln(5)
    
    # --- Vital Health Information ---
    pdf.chapter_title('Vital Health Data')
    pdf.chapter_body('Blood Type', data.get("bt"))
    pdf.chapter_body('Allergies', data.get("al"))
    
    pdf.ln(5)
    
    # --- Medical Conditions & Medications ---
    pdf.chapter_title('Medical History')
    if "con" in data:
        pdf.chapter_body('Conditions', data.get("con"))
    
    if qr_type == "INTAKE" and "med" in data:
        pdf.chapter_body('Medications', data.get("med"))
        
    pdf.ln(5)
        
    # --- Emergency Contacts (SOS Only) ---
    if qr_type == "SOS":
        pdf.chapter_title('Emergency Contact')
        pdf.chapter_body('Name', data.get("cn"))
        pdf.chapter_body('Phone', data.get("cp"))

    # Generate PDF in memory
    pdf_out = pdf.output(dest='S')
    pdf_bytes = pdf_out.encode('latin-1') if isinstance(pdf_out, str) else bytes(pdf_out)
    
    headers = {
        'Content-Disposition': f'attachment; filename="medbridge_{qr_type.lower()}_snapshot.pdf"'
    }
    
    return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
